### ISSUE TITLE
Sending sms 800 contacts

### ISSUE THREAD

**Issue by fabiomicrotel** [markorians/WSMSender#1]
Good morning, thanks for the great work done @markorians .
We tested the application online with a google address with 869 contacts synced with wildix wgw90.
Unfortunately, the system sent 140 sms, with email sms results, but nothing else.
Because? There may be some limitations? some advice?

Thank you very much!
I hope to hear you soon @markorians .

**Comment by markorians** [comment]
Hi @fabiomicrotel

All 869 contact are in the same phonebook?
Maybe only 140 contact are in phonebook selected ?
I need more info.
Please leave a contact in this comment.
After I can set up a debugging process when you have access to PBX and maybe leave more info about its functions .

**Comment by fabiomicrotel** [comment]
Hello @markorians , all contacts are in the same address book selected.
My email is fabionalli@microtelnet.com.
Thanks for your help.

**Comment by markorians** [comment]
At the moment, the maximum limit of record that can be taken from a phonebook is 100. Maybe in future this feature can be removed. 
Adding this limitations to READ ME.
